import java.util.Scanner;
import java.util.Set;
import java.util.TreeSet;

/**
 * Given a string, we have to find out all subsequences of it.
 * A String is a subsequence of a given String, that is generated by
 * deleting some character of a given string without changing its order.
 * Examples:
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc
 */
public class FindSubsequences {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String str = sc.next();
        Set<String> subsequences = findSubsequences(str);

        for (String sub : subsequences) {
            System.out.println(sub);
        }

    }

    private static Set<String> findSubsequences(String str) {
        Set<String> sequences = new TreeSet<String>();
        sequences.add(str);
        if (str.length() > 1) {
            String firstPart = "" + str.charAt(0);
            sequences.add(firstPart);
            String subString = str.substring(1);
            Set<String> subSequences = findSubsequences(subString);
            for (String subSequence : subSequences) {
                sequences.add(subSequence);
                sequences.add(firstPart + subSequence);
            }
        }
        return sequences;
    }
}
